apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
        - name: directus
          image: directus/directus:9
          envFrom:
          - configMapRef:
              name: directus-configmap
          - secretRef:
              name: directus-secrets