apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - directus/deployment.yaml
  - directus/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - react/deployment.yaml
  - react/service.yaml