apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: shankiflang@gmail.com
    privateKeySecretRef:
      name: letsencrypt-token
    solvers:
      - dns01:
          cloudflare:
            email: shankiflang@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "natiq.fr"
